name: Update Naukri Profile

on:
  schedule:
    - cron: "0 4 * * *"   # 9:30 AM IST
    - cron: "0 7 * * *"   # 12:30 PM IST
    - cron: "0 12 24 4 *" # 5:30 PM IST on 24th April
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install

      - name: ▶️ Run script
        run: node index.js
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

      - name: 📤 Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: naukri-debug-screenshots
          path: |
            *.png
            *.html
          if-no-files-found: ignore
